### ISSUE TITLE
'UE4Editor.exe' (Win32): Loaded 'O:\trunk\project\game\Plugins\TAPython\Binaries\Win64\UE4Editor-TAPython.dll'.  Exception thrown at 0x00007FFC8679EE2D (ntdll.dll) in UE4Editor.exe: 0xC0000139: Entry Point Not Found.

### ISSUE THREAD

**Issue by w359405949** [cgerchenhp/UE_TAPython_Plugin_Release#15]
'UE4Editor.exe' (Win32): Loaded 'O:\trunk\project\game\Plugins\TAPython\Binaries\Win64\UE4Editor-TAPython.dll'. 
Exception thrown at 0x00007FFC8679EE2D (ntdll.dll) in UE4Editor.exe: 0xC0000139: Entry Point Not Found.

**Comment by cgerchenhp** [comment]
If possible, please provide more information, such as the engine version, whether the engine is precompiled, the TAPython version, triggering steps, and other information or logs.

**Comment by cgerchenhp** [comment]
**'UE4Editor.exe' (Win32)'** If you are using win32, it's not campatible with the released TAPython, which need 64-bit operating system.
