### ISSUE TITLE
multi-column SListView 的使用

### ISSUE THREAD

**Issue by oscarrr112** [cgerchenhp/UE_TAPython_Plugin_Release#16]
在文档中我看到multi-column SListView里面的示例只能使用文本和富文本，请问能够使用其他类型吗？比如InputText

**Comment by cgerchenhp** [comment]
是的，目前SListView只支持文本和富文本。"使得SListView支持其他控件" 是个很有意思的想法，我会考虑是否在后续版本中添加此功能，当然这也会使得SListView的功能变得更为复杂。

我猜测你的需求是希望添加输入控件，以便用户可以可以直接修改SListView中的问题内容。如果我的猜测不对，欢迎在下面补充。
目前可选的方案有以下几种：

1. SListView的外部有一个共用的输入组件，用于修改当前所在行的文本的修改和确认，例如如下图的最下方的多个文本框：

![016_pic01](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/d9c704d4-c14e-4fd5-abfd-090333802958)


2. 在SListView的右键菜单中，添加一个修改菜单项。点击后会打开一个modal window，用于用户输出文本。例如下图示意
![016_pic02](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/4ab72f6b-46cb-459e-858f-e6321694acf0)

3. 使用SVerticalBox，SHorizontalBox组装出一个拥有多种控件的复合控件，例如下图。如果控件数量很多，可以使用使用ExternalJson功能，加载由脚本创建的机械化的Json文件内容

![016_pic03](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/3ad05731-a98a-4678-b958-5cd9c3246ba3)

如果我的猜测不对，或者有其他确实需要在SListView中使用其他控件的需求，欢迎补充

**Comment by cgerchenhp** [comment]
另外提一下，在下个版本的TAPython中，会计划加入在Python侧动态为当前工具添加组件的功能，不知是否有帮助:D


![016_dynamic](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/80ef798e-9bf6-47b6-a353-8410afc68fc5)
