### ISSUE TITLE
(Beginner) Adding TAPython to PyCharm?

### ISSUE THREAD

**Issue by FiftyTifty** [cgerchenhp/UE_TAPython_Plugin_Release#17]
How do we actually add TAPython to PyCharm? The docs just say:

**In PyCharm, select the <Your_UE_Project>/TA/TAPython/Python directory, right-click, and set it as Sources Root. This will help code navigation and search completion in the /TAPython/Python directory.**

But that makes no sense. Do we add it as an external library in one of the folders listed in the Project pane (DLLs? Lib? Extended Definitions?)? Or...?

Thanks for creating this library btw. Hoping to use it to uatomate converting .wav to .cue and mirroring the folder structure for the .cue file (need to do this a bajillion times for audio assets).

**Comment by cgerchenhp** [comment]
In fact, we have split unreal.py and created the unreal directory through DisUnrealStub.py. There are no other dlls or libs. At the same time, we set the Python directory as "Sources Root" (you need to reopen PyCharm to take effect), so that we can get API auto-completion in PyCharm, as shown in the comparison below.

![set_sources_root_comparison](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/5c004ed2-2e9c-4dbd-b885-ed2b1a0bdeed)

Thank you for your feedback. Regarding the automatic import of audio assets, can you provide some placeholder or experimental resources, especially what's the correct "folder structure for the .cue file"? I don't have much experience with audio-related content, but I am very interested and maybe I can give it a try.

**Comment by FiftyTifty** [comment]
(Attached is an example folder with some .wav sound file duplicated a bunch, named appropriately with the proper folder structure and all. And a Python script that copies the files about in Windows Explorer, to demonstrate what I want to do but in Unreal)

Great stuff. I see where I was probably having an issue; I created the Pycharm project in the typical My Documents folder, not inside the UE project's TAPython folder. Is it possible to have the Python project in a different folder, or does it have to be in that project folder?

Reason for asking, is that there are going to be multiple projects (got 1 already released, 1 has audio finished, 1 is WIP, many more planned), and I have to re-make these same projects for multiple UE versions. Which gets very, very tedious, as each pack has over a hundred music files. The workflow is as follows:

1. Create a new blank project
2. Create a root folder inside Content
3. Inside the root folder, create two subfolders. One called Cues, another called Wavs
4. In Windows Explorer, click and drag the root folder with .wav files in it (end of file name is _Wav.wav)
5. Drop it into the Wavs folder we created in Unreal
6. Create a file filter, to just see .cue and .wav files
7. Select all the wav files -> Right-click -> Create Cue
8. Create the same Unreal folder structure (that Unreal automatically did for the wav files) but in the Cues root folder
9. Click-drag each .cue file from the wav folders, to their corresponding folder in the cue folders
10. For each cue file, replace the _Wav filename suffix with _Cue

If I had to describe this process in a word: BLEH.
It's also prone to human error; dragging into the wrong folder, missing a file, naming it wrong, etc.

[_Example Music Folder.zip](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/files/11736018/_Example.Music.Folder.zip)
[Example Python Script.txt](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/files/11736069/Example.Python.Script.txt)

I have experience with coding (Lua for Total War, Pascal for Bethesda games, C# for some tools). But not with Python, and not with Unreal. So I probably come across as baby bird with this stuff.

**Comment by cgerchenhp** [comment]
The following code snippet can automatically import wave files and create corresponding cues, which can be a reference for your automatic import tool. The execution result is as shown in the gif below. In the import tool, you can add a progress bar, which would enhance the user experience. And you can use TAPython and create a shining UI. Have fun :D

```
import os
from glob import glob
import unreal

source_folder = r"D:\UnrealProjects\5_1\_Example Music Folder\Music_Toolkit_Example"

asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
for wave_file_path in glob(source_folder + '/**/*.wav', recursive=True):
    relative_path = os.path.relpath(wave_file_path, source_folder)

    #1. import the source wave asset
    wave_folder_in_ue = f'/Game/Audio/Wav/{os.path.dirname(relative_path)}'.replace("\\", "/")

    import_task = unreal.AssetImportTask()
    import_task.filename = wave_file_path
    import_task.destination_path = wave_folder_in_ue
    import_task.destination_name = os.path.basename(wave_file_path).split('.')[0]    # no extensions
    import_task.automated = True
    asset_tools.import_asset_tasks([import_task])

    wave_asset_path = f"{wave_folder_in_ue}/{import_task.destination_name}"
    unreal.EditorAssetLibrary.save_asset(wave_asset_path)

    #2. load the create wave asset
    wave_asset = unreal.load_asset(wave_asset_path)

    #3. create the cue asset from the loaded wave asset
    factory = unreal.SoundCueFactoryNew()
    factory.set_editor_property("InitialSoundWaves", [wave_asset])
    cue_folder_in_ue = f'/Game/Audio/Cue/{os.path.dirname(relative_path)}'.replace("\\", "/")
    cue_name = os.path.basename(wave_file_path).split('.')[0].replace('_WAV', '_CUE')
    new_cue = asset_tools.create_asset(cue_name, cue_folder_in_ue, unreal.SoundCue, factory)

    unreal.EditorAssetLibrary.save_asset(new_cue.get_path_name())
```

![G_import_audio_cues](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/b7dd7e2e-a0fd-4c40-b121-fc76d170e8cf)

**Comment by FiftyTifty** [comment]
Oh hell yeah, thanks for doing that. I'll spend some time tinkering about so I properly understand what it's doing. I gotta learn from it, rather than having you do all my homework, aha.

Does that use TAPython? From what I can see, it looks like you're using the standard built-in python for Unreal. So TAPython is for making a UI thingy to call it. Hmm.

The examples in TAPython have a single line of Python attached to the UI, such as:
`"command": "import Utilities, QueryTools; QueryTools.Utils.log_classes(Utilities.Utils.get_selected_assets()[0]) ",`

So would I just replace all line breaks with `;`, or is there a way to define the Python code as a function, and call that instead?

**Comment by cgerchenhp** [comment]
Yes, for simplicity, the above code snippet only uses the built-in Python in Unreal Engine. If you want to add the above Python code to the menu, you can try to put it into your own module, for example, `log_classes` is a method in the `QueryTools.Utils` module. 

In the single line of python in menu config, we only need to import the corresponding package, module, and then execute the methods in it. Just like what you mentioned above, the "dirtiest way" is just paste the code into the `log_classes` which in Utils.py.

**Comment by FiftyTifty** [comment]
Great stuff. I've refactored the code a bit so it's easier for me to read. I'm a diehard camelCase fanatic. And changed the import so it adds _WAV or _CUE, so the tags aren't in the filename itself.

It works great, saves so much time and effort using the script. But there is a problem with Unreal 4:

`LogPython: Error: Exception: SoundCueFactoryNew: Property ‘InitialSoundWaves’ for attribute ‘InitialSoundWaves’ on ‘SoundCueFactoryNew’ is protected and cannot be set`

Same error for `InitialSoundWave`. I tried looking at the documents, but it's just a list of properties. Couldn't find any examples on HotExamples either. Any ideas?

Here's the code:

```import os
from glob import glob
import unreal

strSourcePath = r"D:\UnrealProjects\5_1\_Example Music Folder\Music_Toolkit_Example"
strProjectName = f'PROJ_001/'

asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
for strPathWavCurrent in glob(strSourcePath + '/**/*.wav', recursive=True):

    strPathLocal = os.path.relpath(strPathWavCurrent, strSourcePath)
    #1. import the source wave asset
    strFolderUnreal = f'/Game/{strProjectName}wav/{os.path.dirname(strPathLocal)}'.replace("\\", "/")

    taskImportWav = unreal.AssetImportTask()
    taskImportWav.filename = strPathWavCurrent
    taskImportWav.destination_path = strFolderUnreal
    taskImportWav.destination_name = os.path.basename(strPathWavCurrent).split('.')[0] + '_WAV'    # no extensions
    taskImportWav.automated = True
    
    asset_tools.import_asset_tasks([taskImportWav])

    strPathWavUE = f"{strFolderUnreal}/{taskImportWav.destination_name}"
    unreal.EditorAssetLibrary.save_asset(strPathWavUE)

    #2. load the create wave asset
    assetWavCurrent = unreal.load_asset(strPathWavUE)

    #3. create the cue asset from the loaded wave asset
    factory = unreal.SoundCueFactoryNew()
    factory.set_editor_property("InitialSoundWaves", [assetWavCurrent])
    strPathCueUE = f'/Game/{strProjectName}cue/{os.path.dirname(strPathLocal)}'.replace("\\", "/")
    strCue = os.path.basename(strPathWavCurrent).split('.')[0] + '_CUE'
    assetCueCurrent = asset_tools.create_asset(strCue, strPathCueUE, unreal.SoundCue, factory)

    unreal.EditorAssetLibrary.save_asset(assetCueCurrent.get_path_name())```

**Comment by cgerchenhp** [comment]
The `InitialSoundWaves` property in UE4 is protected in Python, so it cannot be set directly. Clearly, Epic also realized this inconvenience, so it was corrected in UE5. If you are using a C++ project, you can add a Blueprint callable function to set `InitialSoundWaves` for the `factory`. Replace the line `factory.set_editor_property("InitialSoundWaves", [assetWavCurrent])` in Python.
Let me know if you have any question.
