### ISSUE TITLE
Setting Default Values of unreal.PythonStructLib.add_directory_variable

### ISSUE THREAD

**Issue by Aeddon** [cgerchenhp/UE_TAPython_Plugin_Release#2]
Hi Chen, 

I'm using your TAPython to set default values of quite a complicated structure. 
I could do this by "hand", but with 10'000 default values that I need to set, it would take me ages...

Original structure that I want to replicate:
![image](https://user-images.githubusercontent.com/100358557/181118308-37be432b-649c-4c41-9738-7740031b2725.png)

I was able to create the following UserdefinedStructure with the help of your TAPython:
![image](https://user-images.githubusercontent.com/100358557/181118502-6e824f34-83b2-41a9-93ea-d717b9cf2418.png)

But I'm struggling now how to set the default values...
I've found the method "change_variable_default_value" in PythonStructureLib, but this seems not to be fitting for mapped(dict) variables to sub structures. Whatever I try it raised errors. Any clue how to do this?

Here is the output of get_variable_description:
`LogPython: {"VarName": "Characters_2_DF73C88C4D615B7C83C6E1AC881C183A", "VarGuid": "DF73C88C4D615B7C83C6E1AC881C183A", "FriendlyName": "Characters", "DefaultValue": "", "Category": "Name", "SubCategory": "None", "SubCategoryObject": "", "ContainerType": "3", "PinValueType.TerminalCategory": "struct", "PinValueType.TerminalSubCategory": "None", "PinValueType.
TerminalSubCategoryObject": "/Game/CharacterCustomizer/Project_Files/CC_Saved_Variables.CC_Saved_Variables"}`

CHeers & Thanks
Claude

**Comment by cgerchenhp** [comment]
Hi Claude,
Thanks for you feedback.
Yes, it's not easy for users to figure out what the correct "default_value" string is when using  PythonStructLib.change_variable_default_value especially for the complex struct type. A new method has been added to make it easier: PythonStructLib.get_variable_default_value. It will return the default_value in string, then we can tweak it and set the values that we want.

Below is a small example of creating a base struct "CustomPerson" and another struct "Characters" which uses the "CustomPerson" and will been change the default value as your case. Hope it helps.

​Update to the latest [TAPython 1.0.7beta](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/releases/tag/v1.0.7-beta.1) if you get any error messages. I used the new optional parameter: "friendly name" in blow snippet. I'm sure you have a good reason to add "character data" in Struct instead of a datatable. And I added 10,000 values in it with the code below, but the editor UI will be a little laggy: D 

Thank you again for your feedback, it makes this tool better. Let me know if you have any other suggestions. 

BR~


![G010_struct_defaultValues.gif](https://www.tacolor.xyz/images/G010_struct_defaultValues.gif)






```python
import unreal
import random
import sys

# 1.create the struct asset
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
person_struct = asset_tools.create_asset("CustomPerson", "/Game/CreatedByPython", unreal.UserDefinedStruct, unreal.StructureFactory())

if sys.version_info.major == 3 and sys.version_info.minor < 9:
    # UE4
    unreal.PythonStructLib.add_variable(person_struct, category="float", sub_category="", sub_category_object=None, container_type_value=1, is_reference=False, friendly_name="Morph Values")
else:
    # UE5, the real type of float is 'double'
    unreal.PythonStructLib.add_variable(person_struct, category="real",sub_category= "double", sub_category_object=None, container_type_value=1, is_reference=False, friendly_name="Morph Values")
unreal.PythonStructLib.add_variable(person_struct, category="string",  sub_category="", sub_category_object=None, container_type_value=1, is_reference=False, friendly_name="Morph Names")
unreal.PythonStructLib.add_variable(person_struct, category="struct", sub_category="", sub_category_object=unreal.Color.static_struct(), container_type_value=1, is_reference=False, friendly_name="Colors")

unreal.PythonStructLib.add_variable(person_struct, category="name", sub_category="", sub_category_object=None, container_type_value=0, is_reference=False, friendly_name="HairName")
unreal.PythonStructLib.add_variable(person_struct, category="object", sub_category="", sub_category_object=unreal.Texture2D.static_class(), container_type_value=0, is_reference=False, friendly_name="SomeTexture")

# 2.remove the default bool variable, and save the struct
unreal.PythonStructLib.remove_variable_by_name(person_struct, unreal.PythonStructLib.get_variable_names(person_struct)[0])
unreal.EditorAssetLibrary.save_asset("/Game/CreatedByPython/CustomPerson")

# 3.create another struct, which use the 'person_struct'
characters_struct = asset_tools.create_asset("Characters", "/Game/CreatedByPython", unreal.UserDefinedStruct, unreal.StructureFactory())

# 3.1 add a dict variable, key type is name, value type is 'person_struct'
unreal.PythonStructLib.add_directory_variable(characters_struct, category="name", sub_category= "none", sub_category_object=None
                                              , terminal_category="struct", terminal_sub_category="", terminal_sub_category_object=person_struct
                                              , is_reference=False, friendly_name="Characters"
                                              )
# 3.2 also remove the default bool variable
unreal.PythonStructLib.remove_variable_by_name(characters_struct, unreal.PythonStructLib.get_variable_names(characters_struct)[0])
#
guid = unreal.PythonStructLib.get_guid_from_property_name(unreal.PythonStructLib.get_variable_names(characters_struct)[0])
default_str = unreal.PythonStructLib.get_variable_default_value(characters_struct, guid)
print(f"{default_str}")


# 4 set the default values
var_names = unreal.PythonStructLib.get_variable_names(person_struct)
for i, name in enumerate(var_names):
    print(f"{i}: {name}")

# generate the 100 data
my_default_str = "("
for i in range(100):
    if i != 0:
        my_default_str += ', '
    my_default_str += f'("Character_{i}", '
    # Hard code the property_names and gen the random values
    random_morpher_number = random.randint(1, 4)
    _morpher_value_str = ", ".join([str(random.random()) for _ in range(random_morpher_number)])
    _morpher_names_str = ", ".join([f'"Morph_{j}"' for j in range(random_morpher_number)])
    _texture_str = '"/Engine/EngineMaterials/T_DefaultTexture2_D.T_DefaultTexture2_D"' if random.random() > 0.5 else '"/Engine/EngineMaterials/T_Default_MacroVariation.T_Default_MacroVariation"'

    # my_default_str += f'(MorphValues_{i}_{var_names[0]}=(0.200000)'
    my_default_str += f'(MorphValues_{i}_{var_names[0]}=({_morpher_value_str})'
    # my_default_str += f', MorphNames_{i}_{var_names[1]}=("MorphA")'
    my_default_str += f', MorphNames_{i}_{var_names[1]}=({_morpher_names_str})'
    my_default_str += f', Colors_{i}_{var_names[2]}=((B=0,G=0,R={i * 10 % 255},A=255))'
    my_default_str += f', HairName_{i}_{var_names[3]} = "Hair_{i}"'
    my_default_str += f', SomeTexture_{i}_{var_names[4]} = Texture2D\'{_texture_str}\')'

    my_default_str += ')'
my_default_str += ")"

unreal.PythonStructLib.change_variable_default_value(characters_struct, guid, my_default_str)

unreal.EditorAssetLibrary.save_asset("/Game/CreatedByPython/Characters")

```

**Comment by Aeddon** [comment]
Thanks! This is great support for the community! 
I will give it a try!

**Comment by Aeddon** [comment]
Update:
The get_variable_default_value method is returning me an empty string. 
This is because I don't construct the primary struct (in your example "person_struct") with TAPython, 
but simply link the existing UE4 struct (in my case CC_Saved_Variables) from an uasset file:

`unreal.PythonStructLib.add_directory_variable(characters_struct, "Name", "", None,
    "struct", "", unreal.load_asset('/Game/CharacterCustomizer/Project_Files/CC_Saved_Variables.CC_Saved_Variables'), friendly_name="Characters")`

To not have to build that (quite complicated struct) again, I tried the following:
I opened the Characters Struct in UE4 editor, created a default value, then right clicked on the "xx members" column => "copy", 
then used the resulting string as construction template (like you did).

Works like a charm. Thanks for the hint anyway!

Claude

**Comment by cgerchenhp** [comment]
> Update: The get_variable_default_value method is returning me an empty string. This is because I don't construct the primary struct (in your example "person_struct") with TAPython, but simply link the existing UE4 struct (in my case CC_Saved_Variables) from an uasset file:
> 
> `unreal.PythonStructLib.add_directory_variable(characters_struct, "Name", "", None, "struct", "", unreal.load_asset('/Game/CharacterCustomizer/Project_Files/CC_Saved_Variables.CC_Saved_Variables'), friendly_name="Characters")`
> 
> To not have to build that (quite complicated struct) again, I tried the following: I opened the Characters Struct in UE4 editor, created a default value, then right clicked on the "xx members" column => "copy", then used the resulting string as construction template (like you did).
> 
> Works like a charm. Thanks for the hint anyway!
> 
> Claude

The tip of "copy on column" is very useful. Thanks👍
