### ISSUE TITLE
Is there any plan on a Linux Release?

### ISSUE THREAD

**Issue by rhimmelbauer** [cgerchenhp/UE_TAPython_Plugin_Release#21]
I was just wondering if there is a roadmap or any plans on including a Linux release?

Awesome package and it has been very helpful in automating Material changes.

**Comment by cgerchenhp** [comment]
Thank you for your reply. I think at this stage, I don't have the extra energy to maintain a Linux version of TAPython. I don't have much development experience on Linux myself, so I'm very sorry.

**Comment by rhimmelbauer** [comment]
No worries, and thank you for the prompt response. :)
