### ISSUE TITLE
In 4.26，Issue about PythonStructLib

### ISSUE THREAD

**Issue by ADExxxxxx** [cgerchenhp/UE_TAPython_Plugin_Release#24]
I see the doc about add_variable.
<img width="703" alt="微信截图_20230916035026" src="https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/44156367/d565cbf7-f888-4efd-a72b-6fcb429b6927">

bur when I provide the parameter 'friendly_name'，It not work
```python
unreal.PythonStructLib.add_variable(current_struct, "bool", "", None, 0, False, friendly_name="bTest")
```

**Comment by cgerchenhp** [comment]
<img width="912" alt="friend_name" src="https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/assets/1730497/4a6ac978-7d68-4151-b0eb-a9a9661a4088">

Hi, I can’t reproduce this issue in 4.26 of v1.2.0. Also, “friendly_name” needs to be unique in a struct, setting it again will fail if it already exists. I can’t tell if this is what you are encountering, if possible, please provide more information.
