### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by GeorgeR** [cgerchenhp/UE_TAPython_Plugin_Release#25]
Hey, I'm using a custom source build of UE so can't use the precompiled plugins. Is the plugin source available?

**Comment by cgerchenhp** [comment]
Thank you for using TAPython! This repository contains a precompiled binary version of the plugin, and we do not currently provide the source code for it. 

If you have not made significant modifications to the engine, you may try the following steps:

1. rename TAPython.uplugin TAPython.temp, or some other extension name. So the plugin will not be compiled, and the .dll will not be deleted.
2. compile you project 
3. rename the TAPython.temp back to TAPython.uplugin, and modify the BuildID.
4. launch the project.

 We apologize for any inconvenience this may cause. Please let us know if you have any other questions or concerns.

**Comment by GeorgeR** [comment]
Ok, thanks for the clarification.
