### ISSUE TITLE
有办法支持UE编辑器Graph？

### ISSUE THREAD

**Issue by zhang357622852** [cgerchenhp/UE_TAPython_Plugin_Release#26]
编辑器开发，经常涉及到UE的Graph
如果也能用python开发，那就很爽了，

**Comment by cgerchenhp** [comment]
我有尝试做graph相关部分，twitter之前也有一个小演示。但ue中graph种类很多，且很多功能实际实在对应的schema和“编辑器”中实现的，所以完全的自由和通用，并适配各种类型的Graph，还是有难度的。在短期，比如3-6个月之内，没用添加通用型Graph的计划
