### ISSUE TITLE
SnapshotChameleonWindow error！

### ISSUE THREAD

**Issue by 13905316412** [cgerchenhp/UE_TAPython_Plugin_Release#30]
{"Time":"2024-04-02T02:30:31.780Z","Category":"LogOutputDevice","Verbosity":"Warning","Message":"\n\nScript Stack (1 frames) :\n/Script/TAPython.ChameleonData.SnapshotChameleonWindow\n"}
Assertion failed: IsValid() [File:E:\UnrealEngine\Offcial\UE_5.2\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1109] 

已在 UnrealEditor.exe 中执行断点指令(__debugbreak()语句或类似调用)。

0x00007FF9C78FA191 (UnrealEditor-TAPython.dll)处(位于 UnrealEditor.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000218 时发生访问冲突。

**Comment by cgerchenhp** [comment]
方便使用含有pdb版本的pdb版本的TAPython，复现一下报错，并提供下报错时的调用栈信息或log么。另外，提供下调用时的代码或者截图，对于排查问题也是很有帮助的

**Comment by 13905316412** [comment]
偶发性问题，无法复现。建议关闭。
