### ISSUE TITLE
Source code available? 

### ISSUE THREAD

**Issue by mrharris** [cgerchenhp/UE_TAPython_Plugin_Release#31]
Hello

Greatly appreciate the work you are putting into this. Under the AGPL license this project uses I would expect the source code to be available, not just the binaries. Is this something you plan on releasing?

Kind regards

**Comment by michor** [comment]
Hi,

I am also interested in the source code. :)

I hope the source can be made available to the public.

**Comment by cgerchenhp** [comment]
Thank you for your interest in our project! Unfortunately, we're not able to make the source code public at this time due to various constraints. I will let you know if there are any updates on this in the future.
