### ISSUE TITLE
Landscape material layers

### ISSUE THREAD

**Issue by Vorlaak** [cgerchenhp/UE_TAPython_Plugin_Release#34]
Hi,
I am using your plugin to programmatically create landscapes. At the moment, I am able to spawn it and set a Landscape material with layers on it, but it appears black until I apply a Layer info to a layer. Is there a way to do it with Python ?

**Comment by cgerchenhp** [comment]
Yes, we can use `unreal.PythonLandscapeLib.assign_layer_info` to assign layer info to a landscape, and more [here](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release?tab=readme-ov-file#pythonlandscapelib).

**Comment by Vorlaak** [comment]
Thanks, but I am still using UE4.26 and can't upgrade yet, and this version of your plugin isn't available for UE4.26

**Comment by cgerchenhp** [comment]
Now you can download it here [TAPython_4_26_2_win64_v1_2_3_no_pdb.zi](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/releases/download/v1.2.3-ue5.4.4/TAPython_4_26_2_win64_v1_2_3_no_pdb.zip)，or you can download it from this [release page](https://github.com/cgerchenhp/UE_TAPython_Plugin_Release/releases/tag/v1.2.3-ue5.4.4).

**Comment by Vorlaak** [comment]
Thanks, you're a lifesaver !
